### ISSUE TITLE
isNamespaceLoaded() function has the same name as in the "base" R package

### ISSUE THREAD

**Issue by wikiselev** [renozao/pkgmaker#2]
When pkgmaker is attached I get the following warning:

Attaching package: ‘pkgmaker’
The following object is masked from ‘package:base’:
    isNamespaceLoaded

**Comment by renozao** [comment]
Indeed, R 3.2.0 gained a function with the same name.
I am going to rename this function, which also handles environments. I am using it internally and this should have minimal impact on users.
Thanks
